language: php

php:

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.4snapshot"
  include:
    - php: "7.3"
    - php: "7.3"
      env: COVERAGE=1
    - php: "7.4snapshot"

install:
  - composer install

script:
  - ./test-runner.sh

after_success:
  - if [[ ${COVERAGE} == 1 ]]; then travis_retry ./vendor/bin/php-coveralls -v; fi;
