language: php

php:

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
  - php: "7.1"
  - php: "7.2"
    env: COVERAGE=1
  - php: "nightly"

install:
  - composer install

script:
  - ./test-runner.sh

after_success:
 - if [[ ${COVERAGE} == 1 ]]; then travis_retry ./vendor/bin/php-coveralls -v; fi;
